# Step 1 - Copy Files
FROM node:lts as copy-files
 
## Copy everything over to Docker environment
COPY . /usr/src/app/

# Step 2 - Install Dependencies
FROM copy-files as install-dependencies

## Switch to work directory
WORKDIR /usr/src/app

## Install dev packages
RUN npm install --only=dev
RUN npm install -g react-scripts@3.4.1

# Step 3 - Build Docs
FROM install-dependencies as build-docs

## Build project
RUN npm run build-storybook-docs

# Step 4 - Run production server
FROM nginx:stable-alpine

## Copy built files
COPY --from=build-docs /usr/src/app/storybook-static /usr/share/nginx/html

## Copy Conf
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

## Expose port. Used for local Docker build. Will be overridden by Docker Compose
EXPOSE 80

## Run nginx
CMD ["nginx", "-g", "daemon off;"]