const DefaultTrackList = [
  {
    title: 'Streek',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/01 streek.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Eyes',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/02 eyes.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'March',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/03 march.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Downtown',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/04 downtown.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Bad',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/05 bad.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Low Swing',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/06 low swing.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Burn',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/07 burn.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Way West',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/08 way west.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Circus (Interlude)',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/09 groove circus (interlude).mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Move Over',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/10 move over.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Everthing',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/11 everything.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'The Lion',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/12 the lion.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Max',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/13 max.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'How Hot',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/14 how hot.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Cold Static',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/15 cold static.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Dominos',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/16 dominos.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Allure',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/17 allure.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Gang (Solo)',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/18 gang  (solo).mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Faith Fifth',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/19 faith fifth.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Break',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/20 break.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'I Like Party',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/21 i like party.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Frustration',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/22 frustration.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Goblins',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/23 goblins.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Sizzler',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/24 sizzler.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Errant (Interlude)',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/25 errant (interlude).mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Wheels',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/26 wheels.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Crush',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/27 crush.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Advancing',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/28 advancing.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Digi',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/29 digi.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'City 2.0',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/30 city 2.0.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Bounce Quick',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/31 bounce quick.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'These Balls',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/32 these balls.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Grown',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/33 grown.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'King',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/34 king.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Fists of Rage',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/35 fists of rage.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Blam Blam',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/36 blam blam.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Don\'t Know',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/37 don\'t know.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Beep Beep',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/38 beep beep.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Dead',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/39 dead.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: '',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/40 lazy days.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Hot Tofu',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/41 hot tofu.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Grand',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/42 grand.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Curb Music',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/43 curb music.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Horny (Interlude)',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/44 horny (interlude).mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Crushed Smooth',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/45 crushed smooth.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Express',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/46 express.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Big Man',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/47 big man.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Still Dreamin\'',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/48 still dreamin\'.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Keys',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/49 keys.mp3',
    image: '/android-chrome-512x512.png',
  },
  {
    title: 'Advance',
    artist: 'Reckless Tech',
    album: 'The San Francisco Archives - Vol 1',
    audioSrc: '/Music/Reckless Tech - The San Francisco Archives - Vol 1/50 advance.mp3',
    image: '/android-chrome-512x512.png',
  },
];

export default DefaultTrackList;
